### PR TITLE
Fix util test and makefile

### LINKED ISSUE #3: Fix util test
The tests fail: https://travis-ci.com/SkycoinProject/skywire-peering-daemon/builds/146009544#L7

### PR DESCRIPTION
**Pull request by Kifen**
Fixed #3 util_test.go and map nil error, updated `makefile`, `.gitignore` and `READEME.md` files. Also, renamed package `src` to `pkg`.

### CODE REVIEW

File: pkg/daemon/daemon.go [hunk 1]
```diff
@@ -17,41 +17,43 @@ const (
...
 	return &Daemon{
-		PublicKey:  pubKey,
-		RemoteAddr: rAddr,
-		PacketMap:  make(map[string]string),
-		DoneCh:     make(chan error),
-		PacketCh:   make(chan []byte, packetLength),
-		Logger:     logger("SPD"),
-		NamedPipe:  namedPipe,
+		PublicKey: pubKey,
+		localAddr: rAddr,
```
Comment (jdknives) [inline pkg/daemon/daemon.go]: If this is indeed the local address, then `rAddr` as variable name is confusing.
